server:
  port: 8080


eureka:
    client:
      #向注册中心注册自己
      register-with-eureka: true
      #获取注册的东西
      fetch-registry: true
      service-url:
        defaultZone: http://7001.cn:7001/eureka,http://7002.cn:7002/eureka
spring:
  application:
    name: orderfeign



feign:
  client:
    config:
      pay-ment:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 3000
#        readTimeout: 3000
logging:
  level:
    com.yjk.springcloud.order.feign: debug
