server:
  port: 80

eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #获取注册的东西
    fetch-registry: true
    service-url:
      defaultZone: http://7001.cn:7001/eureka
spring:
  application:
    name: hystrix-pay-order

feign:
  hystrix:
    enabled: true
  client:
      config:
        default:
          loggerLevel: full
          readTimeout: 5000
          connectTimeout: 5000

# 全局超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
   level:
     com.yjk: debug
