server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
                port: 5672
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: resvcom

eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #获取注册的东西
    fetch-registry: true
    service-url:
      defaultZone: http://7001.cn:7001/eureka