server:
  port: 3344


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #获取注册的东西
    fetch-registry: true
    service-url:
      defaultZone: http://7001.cn:7001/eureka
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jikuanyu/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master


