server:
  port: 8001





mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yjk.springcloud.entity

spring:
  datasource:
      url: jdbc:mariadb://localhost:6606/test
      username: root
      password: 123456
      driverClassName: org.mariadb.jdbc.Driver
  application:
    name: pay-ment
  zipkin:
     base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1  #采样率值介于θ到1之间，1则表示全部来集


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #获取注册的东西
    fetch-registry: true
    service-url:
      defaultZone: http://7001.cn:7001/eureka,http://7002.cn:7002/eureka

  instance:
    #主机名
    instance-id: instance8001
    #鼠标放上显示ip
    prefer-ip-address: true
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    lease-expiration-duration-in-seconds: 2
    #eureka向服务器发送时间的间隔。默认30
    lease-renewal-interval-in-seconds: 1