server:
  port: 8001





mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yjk.springcloud.entity

spring:
  datasource:
      url: jdbc:mariadb://localhost:6606/test
      username: root
      password: 123456
      driverClassName: org.mariadb.jdbc.Driver
  application:
    name: pay-ment


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #获取注册的东西
    fetch-registry: true
    service-url:
      defaultZone: http://7001.cn:7001/eureka,http://7002.cn:7002/eureka