server:
  port: 80


eureka:
    client:
      #向注册中心注册自己
      register-with-eureka: true
      #获取注册的东西
      fetch-registry: true
      service-url:
        defaultZone: http://7001.cn:7001/eureka,http://7002.cn:7002/eureka
spring:
  application:
    name: order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1